services:
  train:
    build: .
    restart: 'no'
    volumes:
      - /credit_card_fraud_detection/models/:/credit_card_fraud_detection/models
    command: python src/main.py --train

  predict:
    build: .
    restart: 'no'
    volumes:
      - /credit_card_fraud_detection/predictions/:/credit_card_fraud_detection/predictions
    command: python src/main.py --predict
