services:
  train:
    build: .
    restart: 'no'
    volumes:
      - /opt/fraud-detection/models/:/fraud-detection/models
    command: python src/main.py --train

  predict:
    build: .
    restart: 'no'
    volumes:
      - /opt/fraud-detection/predictions/:/fraud-detection/predictions
    command: python src/main.py --predict
